build:
    nodes:
        php700:
            environment:
                php: 7.0.0
        php707:
            environment:
                php: 7.0.7
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
    tests:
        override:
            -
                command: 'composer run tests'
                coverage:
                    file: './coverage/phpunit.clover'
                    format: 'clover'
checks:
    php:
        code_rating: true
        duplication: false
