language: php
matrix:
  include:
    - php: 7.1.3
    - php: 7.1
    - php: 7.2.0
    - php: 7.2
    - php: 7.3.0
    - php: 7.3
    - php: 7.4.0
    - php: 7.4
    - php: 7.4
      env:
        - xdebug=yes
  fast_finish: true
cache:
  files:
    - ./phpunit.cache
    - ./.php_cs.cache
  directories:
    - $HOME/.composer/cache
before_script:
  - if [[ "$xdebug" != "yes" ]]; then phpenv config-rm xdebug.ini; fi
install:
  - travis_retry composer install --no-interaction --no-suggest --prefer-source
script:
  - if [[ "$xdebug" = "yes" ]]; then ./vendor/bin/phpunit; else ./vendor/bin/phpunit --no-coverage; fi
  - if [[ "$xdebug" = "yes" ]]; then ./vendor/bin/infection --min-msi=100; fi
  - composer run static-analysis
