language: php
matrix:
  include:
    - php: 7.1.3
    - php: 7.1
    - php: 7.2.0
    - php: 7.2
    - php: 7.3.0
    - php: 7.3
  fast_finish: true
cache:
  files:
    - ./phpunit.cache
    - ./.php_cs.cache
  directories:
    - ./vendor/
install:
  - travis_retry composer install --no-interaction --no-suggest --prefer-source
script:
  - composer run tests
